powertoys:
	working: ~/AppData/Local/Microsoft/
	configs:
		- settings.json
		- FancyZones/settings.json
firefox:
	backup: ./configs/firefox/
	working: ~/AppData/Roaming/Mozilla/Firefox/Profiles/t240ilq9.default-release/chrome/
	configs:
		- userChrome.css